server:
  port: 8001
  servlet:
    context-path: /map-dice

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/map-dice
    username: jason
    password:
  redis:
    host: 127.0.0.1

mybatis:
  mapper-locations: classpath:mybatis/**.xml

google:
  api:
    key:

