server:
  port: 8001
  servlet:
    context-path: /map-dice

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/map-dice
    username: jason
    password:
  redis:
    host: 127.0.0.1
  mail:
    host: smtp.office365.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    username:
    password:

mail:
  url:

mybatis:
  mapper-locations: classpath:mybatis/**.xml

jwt:
  secret: f4e2e52034348f86b67cde581c0f9eb5
  expire: 604800
  header: Authorization


google:
  api:
    key:

